### ISSUE TITLE
Refer to file-icons

### ISSUE THREAD

**Issue by brettz9** [averrin/color-tabs-regex#18]
As an alternative to color-tabs-regex (if you're indeed no longer maintaining it), I came across some useful info via https://github.com/file-icons/atom#examples that you might like to refer people to (or at least keep this issue open), and it allows one to style tabs beyond just coloring them.

Namely, if one has the `file-icons` package installed, one can use the mappings at https://github.com/file-icons/atom/blob/master/lib/icons/.icondb.js to reference `.js-icon` so as to match recognized JavaScript files (whether the extension is "es6" or "js", etc.

If one doesn't have the package installed, one can still use CSS selectors to match exact extensions like:

```css
.tab > div[data-name$="js"] { /* only matches against file name */
    color: aqua;
}
```

or

```css
.tab > div[data-path$="js"] { /* matches against full file path */
    color: aqua;
}
```

One can get the features of color-tabs by such as:

```css
background-image: linear-gradient(to bottom right, red, yellow);
```

A few other useful tidbits...

To selectively style the active tab:

```css
.tab.active[data-type$="Editor"] {
    font-weight: bold;
}
```

Or to style inactive tabs:

```css
.tab:not(.active) {
    background-color: gray;
}
```

Opacity is a particularly helpful property for such active tabs 0-1.0, e.g., making full opacity for the active tab but low opacity for non-active ones.

```css
.tab:not(.active) {
    color: white;
    opacity: 0.7; /* Reduce somewhat */
}
```

Likewise I find the following properties useful for increasing the relative prominence of the active tab:

```css
.tab.active[data-type$="Editor"] {
    font-weight: 900;
    font-size: 10pt; /* May also wish to fix height of all tabs with this; around 30px? */
    -webkit-text-stroke: 1.20px black;
   /* Possibly also: text-shadow: 2px 2px #ff0000 */
}
```

And to get the gradients (as in color-tabs' [gradients](https://github.com/paulpflug/color-tabs/blob/70de13f29087c14d49f37115c83696ffbf8364e5/lib/color-tabs.coffee#L38-L75)):

```css
background-image: linear-gradient(to bottom right, red, yellow);
```

Or border-color/width/radius from color-tabs' [markers](https://github.com/paulpflug/color-tabs/blob/70de13f29087c14d49f37115c83696ffbf8364e5/lib/color-tabs.coffee#L115-L132)

Or for its [border style and border size/thickness](https://github.com/paulpflug/color-tabs/blob/70de13f29087c14d49f37115c83696ffbf8364e5/lib/color-tabs.coffee#L92-L101).

And if using [`pinned-tabs`](https://atom.io/packages/pinned-tabs), one can style it specifically as well (useful given that there is no text present otherwise with pinned tabs)

```css
.tab.pinned.active[data-type$="Editor"] {
    background-color: white;
}
```

Also useful for tabs, is targeting the close button icon revealed when hovering over tabs:

```css
.tab.active > .close-icon {
    top: 3px; // Change alignment of tabs (here active tabs only; otherwise just target `.tab > .close-icon` or `.tab > .close-icon:not(.active)`)
}
```
